### About the app
**DNBCFoodTextClassifier** is a [RøBÆRTa-base](https://huggingface.co/DDSC/roberta-base-danish) model that can be used for **multi-label classification of food entities from Danish text**. It has been trained to recognise **17 major categories** and **62 subcategories** of food items from Danish text using data from the Danish National Birth Cohort (DNBC). Specifically, this model was trained on a dataset consisting of 38,936 free-text responses to questions regarding specific foods that were introduced and avoided during pregnancy and tested on an additional 4326 responses from the same cohort.

This dashboard allows you to iteratively explore the model’s performance on the test dataset. This model and its performance metrics for each category have been developed as part of the study: **Characterizing food-specific dietary changes during pregnancy using free-text data from the Danish National Birth Cohort** by Erica Elizabeth Eberl, Anne Ahrendt Bjerregaard, Arnór Ingi Sigurdsson, Siddhi Jain, Ann-Marie Hellerung Christiansen, Charlotta Granström, Matthew Paul Gillum, Thorhallur Ingi Halldórsson, Simon Rasmussen, Sjurdur Frodi Olsen, Ruth J.F. Loos, and Marta Guasch-Ferré.

**Note on terminology:** The model performs multi-label classification, meaning each text can belong to multiple food categories at once. In machine learning terminology, these categories correspond to classes (all possible food categories the model can predict) and labels (the specific food categories assigned to each text).

---

### Content

[**Performance Metrics:**](?tab=pm) Explore performance metrics across different food categories and classification levels (major or subcategories).

[**Detailed Plots:**](?tab=dp) Explore prediction scores and feature importance plots of a particular food category.

---

### Types of classifications

**Major Categories:** 17 major food categories of foods and beverages, e.g. Dairy, Fruits, Vegetables and legumes, etc.

**Subcategories:** 62 specific food categories that were combined to create the 17 major food categories, e.g. Flavoured milks, Berries, Tropical fruits, Leaf and stem vegetables, etc.

---

### Technical information


**Software:** R version >= 3.5

**Useful links:** link to paper, link to github repository for paper

